export { default as Landing } from "./Landing";
export { default as Login } from "./Login";
export { default as Signup } from "./SignUp";
export { default as Home } from "./Home";
export { default as User } from "./User";
export { default as Album } from "./Album";
export { default as Photo } from "./Photo";
export { default as Menu } from "./Menu";
export {  default as Footer } from "./Footer";
