export { default as Landing } from "./Landing/Landing";
export { default as Login } from "./Login/Login";
export { default as Signup } from "./Signup/SignUp";
export { default as Home } from "./Home/Home";
export { default as User } from "./User/User";
export { default as Album } from "./Album/Album";
export { default as Photo } from "./Photo/Photo";
export { default as Menu } from "./Menu/Menu";
export {  default as Footer } from "./Footer/Footer";
